ProjectApplication/Controllers/MilkController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using ProjectApplication.Data.Interfaces;
using System.Threading.Tasks;
using ProjectApplication.Data;
using ProjectApplication.ViewModels;
using ProjectApplication.Data.Models;

namespace ProjectApplication.Controllers
{
    public class MilkController: Controller
    {
        private readonly IAllMilks _allMilks;
        private readonly IMilkCategory _allCategories;
        private appDBcontent db;
        
        public MilkController(IAllMilks iallMilks, IMilkCategory imilkCategory, appDBcontent context)
        {
            db = context;
            _allMilks = iallMilks;
            _allCategories = imilkCategory;
        }

        [Route("Milk/List")]
        [Route("Milk/List/{category}")]
        public ViewResult List(string category)
        {
            string _category = category;
            IEnumerable<MilkProd> milks = null;
            string currCategory = "";
            if (string.IsNullOrEmpty(category))
            {
                milks = _allMilks.Milks.OrderBy(i => i.id);
            }
            else
            {
                if(string.Equals("cheese", category, StringComparison.OrdinalIgnoreCase))
                {
                    milks = _allMilks.Milks.Where(i => i.Category.categoryName.Equals("Сыры")).OrderBy(i => i.id);
                    currCategory = "Сыры";
                }else if(string.Equals("milk", category, StringComparison.OrdinalIgnoreCase))
                {
                    milks = _allMilks.Milks.Where(i => i.Category.categoryName.Equals("Цельномолочная продукция")).OrderBy(i => i.id);
                    currCategory = "Цельномолочная продукция";
                }
                else if (string.Equals("kidsMilk", category, StringComparison.OrdinalIgnoreCase))
                {
                    milks = _allMilks.Milks.Where(i => i.Category.categoryName.Equals("Молочные продукты для детей")).OrderBy(i => i.id);
                    currCategory = "Молочные продукты для детей";
                }
                else if (string.Equals("butter", category, StringComparison.OrdinalIgnoreCase))
                {
                    milks = _allMilks.Milks.Where(i => i.Category.categoryName.Equals("Масло")).OrderBy(i => i.id);
                    currCategory = "Масло";
                }
                else if (string.Equals("sgush", category, StringComparison.OrdinalIgnoreCase))
                {
                    milks = _allMilks.Milks.Where(i => i.Category.categoryName.Equals("Молочные консервы")).OrderBy(i => i.id);
                    currCategory = "Молочные консервы";
                }



            }
            var milkObj = new MilksListViewModel
            {
                allMilks = milks,
                currCategory = currCategory,
            };

            return View(milkObj);
        }

        public ViewResult DetailPage(int id)
        {
            var item = _allMilks.Milks.FirstOrDefault(i => i.id == id);
            
            ViewBag.Milk = item.name;
            ViewBag.MilkId = item.id;
            ViewBag.img = item.img;
            ViewBag.fatMass = item.fatMass;
            ViewBag.temperature = item.temperature;
            ViewBag.price = item.price;
            ViewBag.mass = item.mass;
            ViewBag.storageDate = item.storageDate;
            
            
            return View(db.Comments.Where(c => c.MilkProdId == id));
            
            
        }

    }
}

ProjectApplication/Controllers/ShopCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ProjectApplication.Data.Interfaces;
using ProjectApplication.Data.Models;
using ProjectApplication.ViewModels;

namespace ProjectApplication.Controllers
{
    public class ShopCartController: Controller
    {
        private readonly IAllMilks _milkRep;
        private readonly ShopCart _shopCart;

        public ShopCartController(IAllMilks milkRep, ShopCart shopCart)
        {
            _milkRep = milkRep;
            _shopCart = shopCart;
        }

        public ViewResult Index()
        {
            var items = _shopCart.getShopItems();
            _shopCart.listShopitems = items;

            var obj = new ShopCartViewModel
            {
                shopCart = _shopCart
            };

            return View(obj);

        }
        
        public RedirectToActionResult addToCart(int id)
        {Console.Write("OK");
            var item = _milkRep.Milks.FirstOrDefault(i => i.id == id);

            if (item != null){  
                _shopCart.AddToCart(item);
            }
            return RedirectToAction("Index");

        }
    }
}

ProjectApplication/Views/Shared/AllMilks.cshtml
@model MilkProd

<link href="~/css/style.css"/>
<div class="vm-col-3 vertical-separator box ml-4" style="margin: 40px">
    <div class="align-items-center">
        <a asp-controller="Milk" asp-action="DetailPage" asp-route-id="@Model.id">
            <img src="@Model.img" width="300" height="300" class="browseProductImage">
            <p class="truncate-text">@Model.name</p>
        </a>
    </div>
    <div class ="center">
        <a class="btn btn-primary" asp-controller="ShopCart" asp-action="addToCart" asp-route-id="@Model.id">
                   Добавить в корзину
        </a>
    </div>
</div>
<style>
    .box {
        border-radius: 10px; /* Радиус границ*/
        box-shadow: 0 0 15px #A9A9A9; /* Размер и цвет тени блока*/
    }
</style>
<style>
    .truncate-text {
        padding: 1rem;
        width: 200px;
        height: 80px;
        overflow: hidden;
        position: relative;
    }
    .center {
        text-align: center;
    }
        .truncate-text:after {
            content: "";
            position: absolute;
            left: 0;
            bottom: 0;
            width: 100%;
            height: 40px;
            background: linear-gradient(180deg, transparent,#ffffff 50%);}
</style>

ProjectApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html style="font-size: 16px;">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <meta name="keywords" content="Хорошая еда -Хорошее настроение​, Рогачевский&nbsp;молочноконсервный комбинат">
    <meta name="description" content="">
    <meta name="page_type" content="np-template-header-footer-from-plugin">
    <title>Главная</title>
    <link rel="stylesheet" href="/css/nicepage.css" media="screen">
    <link rel="stylesheet" href="/css/main.css" media="screen">
    <link href="~/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script class="u-script" type="text/javascript" src="/js/jquery.js" defer=""></script>
    <script class="u-script" type="text/javascript" src="/js/nicepage.js" defer=""></script>
    <meta name="generator" content="Nicepage 3.1.0, nicepage.com">



    <link id="u-theme-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i|Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i">
    <link id="u-page-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Oswald:200,300,400,500,600,700">


    <meta property="og:title" content="Главная">
    <meta property="og:type" content="website">
    <meta name="theme-color" content="#478ac9">
    <link rel="canonical" href="index.html">
    <meta property="og:url" content="index.html">

</head>

<body data-home-page-title="Главная" class="u-body">
    <header class="u-clearfix u-header u-header" id="sec-856f">
        <div class="u-clearfix u-sheet u-sheet-1" style="background: #FFFFFF">
            <a href="#" class="u-image u-logo u-image-1" data-image-width="296" data-image-height="230">
                <img src="~/img/Logo.jpg" class="u-logo-image u-logo-image-1" data-image-width="111.5">
            </a>
            <nav st class="u-menu u-menu-dropdown u-offcanvas u-menu-1" style="background-color: #FFFFFF">
                <div class="menu-collapse" style="font-size: 1rem; letter-spacing: 0px;">
                    <a class="u-button-style u-custom-left-right-menu-spacing u-custom-padding-bottom u-custom-top-bottom-menu-spacing u-nav-link u-text-active-palette-1-base u-text-hover-palette-2-base" href="#">
                        <svg><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#menu-hamburger"></use></svg>
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                            <defs>
                                <symbol id="menu-hamburger" viewBox="0 0 16 16" style="width: 16px; height: 16px;">
                                    <rect y="1" width="16" height="2"></rect>
                                    <rect y="7" width="16" height="2"></rect>
                                    <rect y="13" width="16" height="2"></rect>
                                </symbol>
                            </defs>
                        </svg>
                    </a>
                </div>
                <div class="u-custom-menu u-nav-container">
                    <ul class="u-nav u-unstyled u-nav-1">
                        <li class="u-nav-item">
                            <a class="u-button-style u-nav-link u-text-active-palette-1-base u-text-hover-palette-2-base" href="/Home/Index" style="padding: 10px 36px;">Главная</a>
                        </li>
                        <li class="u-nav-item">
                            <a class="u-button-style u-nav-link u-text-active-palette-1-base u-text-hover-palette-2-base" href="/Home/Production" style="padding: 10px 36px;">Продукция</a>
                        </li>
                        <partial name="_LoginPartial" />


                    </ul>
                </div>
                
                <div class="u-custom-menu u-nav-container-collapse">
                    <div class="u-black u-container-style u-inner-container-layout u-opacity u-opacity-95 u-sidenav">
                        <div class="u-sidenav-overflow">
                            <div class="u-menu-close"></div>
                            <ul class="u-align-center u-nav u-popupmenu-items u-unstyled u-nav-2">
                                <li class="u-nav-item">
                                    <a class="u-button-style u-nav-link" href="Главная.html" style="padding: 10px 36px;">Главная</a>
                                </li>
                                <li class="u-nav-item">
                                    <a class="u-button-style u-nav-link" style="padding: 10px 36px;">Продукция</a>
                                </li>
                                <li class="u-nav-item">
                                    <a class="u-button-style u-nav-link" style="padding: 10px 36px;">Корзина</a>
                                </li>
                                <li class="u-nav-item">
                                    <a class="u-button-style u-nav-link" style="padding: 10px 36px;">Вход</a>
                                </li>
                                <li class="u-nav-item">
                                    <a class="u-button-style u-nav-link" style="padding: 10px 36px;">Регистрация</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="u-black u-menu-overlay u-opacity u-opacity-70"></div>
                </div>
            </nav>
        </div>
    </header>    
    
    @RenderBody()
    @RenderSection("Scripts", required: false)
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script>
      AOS.init();
    </script>
</body>

</html>